using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace pryEvolvedTrinityGuard.Classes
{
    public class Character
    {
        int _guid;
        int _account;
        string _name;
        int _race;
        int _class;
        int _gender;
        int _level;
        int _xp;
        int _money;
        int _playerBytes;
        int _playerBytes2;
        int _playerFlags;
        float _position_x;
        float _position_y;
        float _position_z;
        int _map;
        int _instance_id;
        int _instance_mode_mask;
        float _orientation;
        string _taximask;
        int _online;
        int _cinematic;
        int _totaltime;
        int _leveltime;
        int _logout_time;
        int _is_logout_resting;
        float _rest_bonus;
        int _resettalents_cost;
        int _resettalents_time;
        float _trans_x;
        float _trans_y;
        float _trans_z;
        float _trans_o;
        int _transguid;
        int _extra_flags;
        int _stable_slots;
        int _at_login;
        int _zone;
        int _death_expire_time;
        string _taxi_path;
        int _arenaPoints;
        int _totalHonorPoints;
        int _todayHonorPoints;
        int _yesterdayHonorPoints;
        int _totalKills;
        int _todayKills;
        int _yesterdayKills;
        int _chosenTitle;
        int _knownCurrencies;
        int _watchedFaction;
        int _drunk;
        int _health;
        int _power1;
        int _power2;
        int _power3;
        int _power4;
        int _power5;
        int _power6;
        int _power7;
        int _latency;
        int _talentGroupsCount;
        int _activeTalentGroup;
        string _exploredZones;
        string _equipmentCache;
        int _ammoId;
        int _knownTitles;
        int _actionBars;
        int _grantableLevels;
        int _deleteInfos_Account;
        string _deleteInfos_Name;
        int _deleteDate;

    }
}
